upstream zeta_app {
    server web:8000;
}

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name 89.104.69.135 zeta-strategy.ru www.zeta-strategy.ru;
    return 301 https://$host$request_uri;
}

# SSL Server
server {
    listen 443 ssl;
    server_name zeta-strategy.ru www.zeta-strategy.ru;

    ssl_certificate /etc/nginx/certs/zeta.crt;
    ssl_certificate_key /etc/nginx/certs/zeta.key;

    # Basic SSL optimizations
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    location / {
        proxy_pass http://zeta_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
}
