# Generated by Django 6.0.3 on 2026-04-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_multiplayerroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayerroom',
            name='guest_gold_server',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='multiplayerroom',
            name='guest_units_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='multiplayerroom',
            name='host_gold_server',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='multiplayerroom',
            name='host_units_count',
            field=models.IntegerField(default=2),
        ),
    ]
