# Generated by Django 5.2 on 2026-04-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_player_playergold'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayerroom',
            name='game_version',
            field=models.IntegerField(default=0),
        ),
    ]
